### ISSUE TITLE
Add support for `jsonb` type column check

### ISSUE THREAD

**Issue by nicola-auriti** [dbkover/dbkover#16]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to verify the value of table columns defined as `jsonb`. This currently seems to be a limitation of DBUnit.
In fact, by running the tests on an application declaring a table with a column defined as `jsonb`, the following message is logged in the console:

```
org.dbunit.util.SQLHelper - <table-name>.<column-name> data type (1111, 'jsonb') not recognized and will be ignored. See FAQ for more information.
```

**Describe the solution you'd like**
According to some info found while googling, it seems to be possible to extend DBUnit to add the support to such `jsonb` fields. See https://stackoverflow.com/a/53559173/18663569 for an example of how to declare the new custom type, and http://dbunit.wikidot.com/datatypefactory as an example of how you can then use that custom type to override the default implementation.

**Describe alternatives you've considered**
I'm not sure of what the alternatives might be.

**Additional context**
Nothing to add.

**Comment by sunnhas** [comment]
@nicola-auriti I've added a PR in #17 which add's the `jsonb` datatype for postgres as described with an extension. I will be preparing a release of this later today.
