### ISSUE TITLE
Potential DB connections starvation issue in DBKoverExecutor

### ISSUE THREAD

**Issue by nicola-auriti** [dbkover/dbkover#25]
**Describe the bug**
Right now the current implementation of `core/src/main/kotlin/io/dbkover/DBKoverExecutor.kt` can lead to a connection pool starvation in case the provider function annotated with `@DBKoverConnection` doesn't make sure of providing a reusable connection.
This happens because both `beforeTest` and `afterTest` functions invoke `getDatabaseConnection(schema)`, which invokes the `@DBKoverConnection` function. If such function is implemented as:

```kotlin
@DBKoverConnection
fun dbConnection() = datasource.getConnection()
```

that might result in a new DB connection being created every time, with at least 2 connections being opened for tests annotated with both `@DBKoverDataSet` & `@DBKoverExpected`. This means that the running test environment, in this case, must be able to provide a connection pool of at least size 2.

**To Reproduce**
1. You can set up an integration test that uses DBKover and has the following:
    - A provider function annotated with `@DBKoverConnection` implemented as above
    - A test function that is both annotated with `@DBKoverDataSet` & `@DBKoverExpected`
    - A test runtime that is configured to rely on a DB connection pool of just 1 connection
    - Set a reasonably short connection timeout for DB connection
3. Execute the test
4. The test should fail with a connection timeout

**Expected behavior**
I would expect such example test not to fail. The executor should rely on a shared single connection to the DB. Such connection instance might even be added to the test execution context and be available for injection in the test.
This way a test can be implemented/executed by relying on a single connection.
Ideally it shouldn't be a responsibility of the library consumer to take care of providing a reusable connection to the `@DBKoverConnection` function.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by sunnhas** [comment]
Hi @nicola-auriti. Thanks for reporting this issue.

The intention was never to use a datasource for providing connections in tests. Nevertheless I think it's important for DBKover to manage the connections it needs internally. For that reason, I've changed the behaviour of how DBKover uses db connections, so it's now only required to provide connection details like jdbc url and username/password. (see https://github.com/dbkover/dbkover/pull/27 for reference) I believe this will resolve this issue, if it doesn't, please report back 😊
